Exponential backoff for fluentd log shipping
wazo-platform/wazo-js-sdk pull request #704
Opened 2023-05-04 20:08 UTC by DrPyser

To avoid hammering unstable fluentd, changed retry algorithm to use exponential backoff with random jitter.

2023-05-04 20:12 UTC, manuquentin requested changes

2023-05-04 20:12 UTC, manuquentin commented on src/service/IssueReporter.ts
> +    const waitfn = (attempt: number, initial = 5000, maxWait = 50000) => {
Can we have the `waitFn` outside of the `_sendDebugToGrafana` method ?
And maybe we can call it `_computeNextAttemptDelay`.

2023-05-05 13:25 UTC, DrPyser commented
btw spent some time trying to add a test case for _sendToGrafana, but had trouble verifying my expectation around the behavior of the promise chains. Opted for the simpler case, but will add test coverage for the wait function.

2023-05-08 14:41 UTC, manuquentin approved these changes

2023-05-08 14:41 UTC, merged